server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: country-service
              uri: ${COUNTRY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/countries/**

            - id: city-service
              uri: ${CITY_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/cities/**

            - id: weather-service
              uri: ${WEATHER_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/weather/**