CREATE TABLE cities (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        country_code VARCHAR(2)       NOT NULL,
                        name         VARCHAR(100)     NOT NULL,
                        latitude     DOUBLE PRECISION NOT NULL,
                        longitude    DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_cities_country_code ON cities (country_code);