CREATE TABLE countries (
                           id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code VARCHAR(2)   NOT NULL UNIQUE,
                           name VARCHAR(100) NOT NULL
);