spring.application.name=city-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:citydb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false